### ISSUE TITLE
Feature Layer != FeatureServer

### ISSUE THREAD

**Issue by slibby** [dmfenton/koop-zillow#1]
So I think there’s something in the routes that isn't quite right – or in the invoking of BaseController – basically, for the /gist sample, these two urls return different results:
• http://server:1337/gist/6021269/FeatureServer/0
• http://server:1337/gist/6021269/FeatureServer

where in my use of the Zillow provider, they do not, they return the same info:
• http://server:1337/zillow/boulder,co/FeatureServer/0
• http://server/zillow/boulder,co/FeatureServer

I noticed in routes/index.js all the routes point to 'featureserver' instead of 'featureservice' as they do in the koop-gist routes. Also wasn't sure if there was something about the order of routes.

Let's discuss more when back online.

**Comment by dmfenton** [comment]
Fixed by https://github.com/dmfenton/koop-zillow/commit/de079804b19ba76dd7f2018a41cb52066db77fd4#diff-ee24f04f6f1f0b831039be4b6494739bR20

I really need tests...

**Comment by dmfenton** [comment]
Ok got it this time. Basically the problem was that I am a JS n00b
